version: '3.2'
services:
  couchdb:
    image: "couchdb:3.2.2"
    environment:
      COUCHDB_USER: dbadmin
      COUCHDB_PASSWORD: dbadmin
    ports:
      - "5984:5984"
    external_links:
      - couchdb2:second
    volumes:
      - "./couch.ini:/opt/couchdb/etc/local.d/docker.ini"

  couchdb2:
    image: "couchdb:3.2.2"
    environment:
      COUCHDB_USER: dbadmin
      COUCHDB_PASSWORD: dbadmin
    ports:
      - "5985:5984"
    external_links:
      - couchdb:first
    volumes:
      - "./couch.ini:/opt/couchdb/etc/local.d/docker.ini"
